#:kivy 2.0.0

<CustomLabel@Label>:
    padding: ('20dp', '20dp', '20dp', '20dp')
    text_size: self.width, None
    size_hint: 0.5, None
    texture_size: None, None
    color: 0, 0, 0, 1
    halign: 'left'
    valign: 'top'

<Container>:
    rows: 5

    CustomLabel:
        id: label
        text: 'Добро пожаловать в чат!'

    BoxLayout:
        orientation: 'horizontal'
        MDTextField:
            id: text_input
            required: True
            hint_text: 'Что хотите узнать?'
            multiline: False
            size_hint: 1, 0
            background_color: 0.8, 0.8, 0.8, 1
            on_text: root.on_text_change(self.text)

        MDRoundFlatButton:
            id: button_send
            icon: "pancil"
            text_color: "darkblue"
            disabled: True
            text: 'Отправить.'
            size_hint: 0.1, 0.0
            background_color: 0.3, 0.6, 0.9, 1
            on_release:
                root.send_message_async()

    # Добавляем TextInput для обработки изменения размера клавиатуры
    TextInput:
        id: keyboard_helper
        size_hint_y: None
        height: 0
